# Generated by Django 6.0.3 on 2026-04-06 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxpayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ПІБ платника')),
                ('tin', models.CharField(max_length=10, unique=True, verbose_name='ІПН')),
            ],
        ),
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва податку')),
                ('rate', models.FloatField(verbose_name='Ставка (%)')),
            ],
        ),
        migrations.CreateModel(
            name='TaxRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Сума до сплати')),
                ('taxpayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxes.taxpayer', verbose_name='Платник')),
                ('tax_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxes.taxtype', verbose_name='Тип податку')),
            ],
        ),
    ]
