# Generated by Django 6.0.3 on 2026-04-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0002_taxpayer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrecord',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Статус оплати'),
        ),
    ]
