# Generated by Django 6.0.3 on 2026-04-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0003_taxrecord_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrecord',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
