"""flask initial

Revision ID: 84b8e57bacf8
Revises: 
Create Date: 2026-04-21 17:11:31.100375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84b8e57bacf8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taxpayers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('tin', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tin')
    )
    op.create_table('tax_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taxpayer_id', sa.Integer(), nullable=False),
    sa.Column('tax_type_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tax_type_id'], ['tax_types.id'], ),
    sa.ForeignKeyConstraint(['taxpayer_id'], ['taxpayers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_records')
    op.drop_table('taxpayers')
    op.drop_table('tax_types')
    # ### end Alembic commands ###
